apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources: 
- replicaset.yml
- service.yml

configMapGenerator:
  - name: ${parameters['appname']}-properties
    files:
      - application-k8s.yaml