apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: ${appname}
  namespace: ${namespace}
  annotations:
    strategy.spinnaker.io/versioned: 'false'
    strategy.spinnaker.io/recreate: 'true'
  labels:
    app: ${appname}
    type: back-end
spec:
  template:
    metadata:
      name: ${appname}
      labels:
        app: ${appname}
        type: back-end
    spec:
      volumes:
          - name: ${parameters['appname']}-properties
            configMap:
              name: ${parameters['appname']}-properties
      containers:
        - name: ${appname}
          image: app-image
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: k8s
          envFrom:
            - configMapRef:
                name: spotme-config
            - configMapRef:
                name: ${parameters['appname']}-config
            - secretRef:
                name: spotme-db-secrets
          volumeMounts:
          - name: ${parameters['appname']}-properties
            mountPath: /config # The directory path inside the container
            readOnly: true
          # --- ADDED PROBES HERE ---
          readinessProbe:
            httpGet:
              path: /actuator
              port: 8080
            initialDelaySeconds: 60 # Time to wait before first readiness check
            periodSeconds: 5        # How often to perform the check
            timeoutSeconds: 3       # Timeout for the request
          livenessProbe:
            httpGet:
              path: /actuator
              port: 8080
            initialDelaySeconds: 60 # Allow more time for initial startup
            periodSeconds: 10       # How often to perform the check
            failureThreshold: 5     # Number of consecutive failures before restarting
            timeoutSeconds: 3                      
  replicas: 1
  selector:
    matchLabels:
      app: ${appname}
