apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${appname}
  annotations:
      strategy.spinnaker.io/recreate: 'true'
  labels:
    app: ${appname}
    type: back-end
spec:
  template:
    metadata:
      name: ${appname}
      labels:
        app: ${appname}
        type: back-end
    spec:
      containers:
        - name: spotme-rest
          image: containerregistry.spot-me-app.com/spotme/spotme-rest:develop
          imagePullPolicy: Always
          resources:
            requests:
              memory: "1000Mi"
              cpu: "500m"
            limits:
              memory: "3000Mi"
              cpu: "1000m"
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: spotme-config
            - secretRef:
                name: spotme-db-secrets
      imagePullSecrets:
        - name: jfrog-dev
  replicas: 1
  selector:
    matchLabels:
      app: spotme-rest
