apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: ${appname}
  namespace: ${namespace}
  annotations:
      strategy.spinnaker.io/recreate: 'true'
  labels:
    app: ${appname}
    type: back-end
spec:
  template:
    metadata:
    spec:
      containers:
        - name: ${appname}
          imagePullPolicy: Always
          resources:
            requests:
              memory: "1000Mi"
              cpu: "500m"
            limits:
              memory: "3000Mi"
              cpu: "1000m"
          envFrom:
            - configMapRef:
                name: spotme-config
            - secretRef:
                name: spotme-db-secrets
      imagePullSecrets:
        - name: jfrog-dev