apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: spotme-mysql-pvc-dev
  namespace: spotme-dev
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: manual
  volumeMode: Filesystem
  volumeName: spotme-mysql-pv-dev
status:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 5Gi
  phase: Bound