apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: ${appname}
  namespace: ${namespace}
  annotations:
    strategy.spinnaker.io/versioned: 'false'
    strategy.spinnaker.io/recreate: 'true'
  labels:
    app: ${appname}
    type: back-end
spec:
  template:
    metadata:
      name: ${appname}
      labels:
        app: ${appname}
        svc: ${appname}
        type: back-end
    spec:
      containers:
        - name: ${appname}
          image: app-image
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: k8s
            - name: MY_NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          envFrom:
            - configMapRef:
                name: ${parameters['appname']}-config  
            - configMapRef:
                name: ${parameters['appname']}-properties
            - secretRef:
                name: spotme-db-secrets
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 10                     
  replicas: 1
  selector:
    matchLabels:
      app: ${appname}
