apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: ${appname}
  namespace: ${namespace}
  annotations:
    strategy.spinnaker.io/versioned: 'false'
    strategy.spinnaker.io/recreate: 'true'
  labels:
    app: ${appname}
    type: back-end
spec:
  template:
    metadata:
      name: ${appname}
      labels:
        app: ${appname}
        type: back-end
    spec:
      containers:
        - name: ${appname}
          image: app-image
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: spotme-config
            - secretRef:
                name: spotme-db-secrets     
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 120 # Time to waits before first readiness check
            periodSeconds:  30       # How often to perform the check
            timeoutSeconds: 10     # Timeout for the request
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 240 # Allow more time for initial startup
            periodSeconds: 30       # How often to perform the check
            failureThreshold: 7     # Number of consecutive failures before restarting
            timeoutSeconds: 10                  
  replicas: 1
  selector:
    matchLabels:
      app: ${appname}
