apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${appname}
  namespace: ${namespace}
  annotations:
      strategy.spinnaker.io/recreate: 'true'
  labels:
    app: ${appname}
    type: back-end
spec:
  template:
    metadata:
      name: ${appname}
      labels:
        app: ${appname}
        type: back-end
    spec:
      containers:
        - name: ${appname}
          image: app-image
          ports:
            - containerPort: 8080
      imagePullSecrets:
        - name: regcred
  replicas: 1
  selector:
    matchLabels:
      app: ${appname}
