apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: spotme-mysql-pvc-prod
  namespace: spotme-prod
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
  storageClassName: manual
  volumeMode: Filesystem
  volumeName: spotme-mysql-pv-prod