apiVersion: v1
kind: Service
metadata:
    name: spotme-db-service
    labels:
      app: db-service
spec:
  type: NodePort
  selector: 
    app: spotme-db
  ports:
    - port: 3306
      targetPort: 3306
      nodePort: 30006

