apiVersion: apps/v1
kind: Deployment
metadata:
  name: spotme-db
  namespace: spotme-prod
  annotations:
    strategy.spinnaker.io/versioned: 'false'
    strategy.spinnaker.io/recreate: 'true'
  labels:
    app: spotme-db
spec:
  selector:
    matchLabels:
      app: spotme-db
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: spotme-db
    spec:
      containers:
        - image: mysql:8.0-debian
          name: spotme-db
          resources:
            requests:
              memory: "1000Mi"
              cpu: "500m"
            limits:
              memory: "3000Mi"
              cpu: "1000m"
          # env:
          #   - name: MYSQL_ROOT_PASSWORD
          #     valueFrom:
          #       secretKeyRef:
          #         name: spotme-db-secrets
          #         key: password
          #   - name: DB_USERNAME
          envFrom:
            - secretRef:
                name: spotme-db-secrets
          ports:
            - containerPort: 3306
              name: mysql
          volumeMounts:
            - name: spotme-mysql-storage
              mountPath: /var/lib/mysql
      volumes:
        - name: spotme-mysql-storage
          persistentVolumeClaim:
            claimName: spotme-mysql-pvc-prod
