apiVersion: v1
kind: ConfigMap
metadata:
  name: ${appname}-config
  annotations:
    strategy.spinnaker.io/versioned: 'false'
    strategy.spinnaker.io/recreate: 'true'
data:
  BASE_URL: https://gate-${environment}.spotme-app.com
  USER_SVC_URL: spotme-user-svc.spotme-${environment}.svc.cluster.local  
  MATCH_SVC_URL: spotme-match-svc.spotme-${environment}.svc.cluster.local  
  GYM_SVC_URL: spotme-gym-svc.spotme-${environment}.svc.cluster.local  
  FRIENDS_SVC_URL: spotme-friends-svc.spotme-${environment}.svc.cluster.local  
  AUTH_SVC_URL: spotme-auth-svc.spotme-${environment}.svc.cluster.local
  UI_SVC: spotme-ui-svc.spotme-${environment}.svc.cluster.local


