apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ${parameters['appname']}-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
    - host: ${parameters['appname']}.dev.mts-local.com
      http:
        paths:
          - path: /auth-ingress
            pathType: Prefix
            backend:
              service:
                name: spotme-auth-svc
                port:
                  number: 80