apiVersion: v1
kind: Service
metadata:
  name: ${parameters['appname']}-lb
  labels:
    app: ${parameters['appname']}
spec:
  type: LoadBalancer
  selector:
    app: ${parameters['appname']}
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080