apiVersion: v1
kind: Service
metadata:
    name: spotme-web-service
    labels:
      app: web-service
spec:
  type: NodePort
  selector: 
    app: spotme-web
  ports:
    - port: 5173
      targetPort: 5173
      nodePort: 30273

