apiVersion: v1
kind: Service
metadata:
    name: spotme-backend-service
    annotations:
      strategy.spinnaker.io/recreate: 'true'
    labels:
      app: backend-service
spec:
  type: NodePort
  selector: 
    app: spotme-rest
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30280

