apiVersion: v1
kind: ConfigMap
metadata:
  name: spotme-config
  annotations:
    strategy.spinnaker.io/versioned: 'false'
    strategy.spinnaker.io/recreate: 'true'
data:
  DB_URL: "jdbc:mysql://spotme-db-service.spotme-prod.svc.cluster.local/spotme_prod?autoReconnect=true&useSSL=false&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC&allowPublicKeyRetrieval=true"
  DB_BEHAVIOR: "update"
  DB_DRIVER: "com.mysql.cj.jdbc.Driver"
  DB_DIALECT: "org.hibernate.dialect.MySQLDialect"
  CUSTOM_PORT: "8081"
  REST_ORIGIN: https://rest.spot-me-app.com
  VITE_REST_ORIGIN: https://rest.spot-me-app.com
  UI_ORIGIN: https://ui.spot-me-app.com
  DEV_URL: https://rest.spot-me-app.com
  PROD_URL: "https://rest.spot-me-app.com"
