apiVersion: apps/v1
kind: Deployment
metadata:
  name: spotme-rest-deployment
  annotations:
    strategy.spinnaker.io/versioned: 'false'
    strategy.spinnaker.io/recreate: 'true'
  labels:
    app: spotme-rest
    type: back-end

spec:
  template:
    metadata:
      name: spotme-rest
      labels:
        app: spotme-rest
        type: back-end
        project: spotme
    spec:
      containers:
        - name: spotme-rest
          image: containerregistry.spot-me-app.com/spotme/spotme-rest:release
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: spotme-config
            - secretRef:
                name: spotme-db-secrets
      imagePullSecrets:
        - name: jfrog-dev
  replicas: 1
  selector:
    matchLabels:
      app: spotme-rest
