apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${appname}
  namespace: ${namespace}
  annotations:
    strategy.spinnaker.io/recreate: 'true'
  labels:
    app: ${label}
spec:
  selector:
    matchLabels:
      app: ${label}
  template:
    metadata:
      labels:
        app: ${label}
    spec:
      containers:
        - image: mysql:8.0-debian
          name: ${appname}
          resources:
            requests:
              memory: "1000Mi"
              cpu: "500m"
            limits:
              memory: "3000Mi"
              cpu: "1000m"
          envFrom:
            - secretRef:
                name: spotme-db-secrets
          ports:
            - containerPort: 3306
              name: mysql
          volumeMounts:
            - name: spotme-mysql-storage-${environment}
              mountPath: /var/lib/mysql
      volumes:
        - name: spotme-mysql-storage-${environment}
          persistentVolumeClaim:
            claimName: spotme-mysql-pvc-${environment}
